### ISSUE TITLE
Incompatibility with mods adding lights

### ISSUE THREAD

**Issue by darock830** [GeForceLegend/SEUS_PTGI_GFME#43]
As the only shader in existence that supports both raytracing and distant horizons, this shader is absolutely phenomenal.
But I just wanted to bring your attention to its incompatibility with any mods that use transparent textures or add lights. (e.g., Crayfish furniture lamps, Yuushya's lamps, etc.--transparent textures like windows have weird watery waves)
I know that this shader is developed with vanilla rendering in mind, but...
It will be such a cherry on top for it have support for particles (for magic mods), transparent textures, and mod-added lights.

Anyways,
Thank you again for your hard work! Whether you make adjustments or not, I still love your work.

**Comment by GeForceLegend** [comment]
Most block related mod incompatibility can be saved with adding them into `block.properties`. However, I cannot add blocks of all mods into it, so this can only be added by users. If something cannot be fixed by this, then it mostly would be incompatibility with Optifine shader pipeline and that mod, which I won't fix.
